name: deploy-dockerhub
on: [ workflow_dispatch ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: get tag version
        id: get_tag_version
        run: |
          sudo apt-get install libxml2-utils
          echo ::set-output \
            name=VERSION::$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
      - name: docker push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: xcoo/cruler
          tags: ${{ steps.get_tag_version.outputs.VERSION }}
