name: lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: clojure:openjdk-11-tools-deps
    steps:
      - uses: actions/checkout@v2
      - name: Run lint
        run: clj -Alint
