# ref: https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images
# You can find the image on: https://github.com/xcoo/cruler/packages
name: snapshot-push
on:
  push:
    branches:
      - main
jobs:
  docker_push:
    name: snapshot push
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: get tag version
        id: get_tag_version
        run: |
          sudo apt-get install libxml2-utils
          echo ::set-output \
            name=VERSION::$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" pom.xml)

      - name: snapshot push
        if: endsWith(steps.get_tag_version.outputs.VERSION, '-SNAPSHOT')
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: xcoo/cruler/cruler
          tags: ${{ steps.get_tag_version.outputs.VERSION }}
