name: validate
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: clojure:openjdk-11-tools-deps
    steps:
      - uses: actions/checkout@v2
      - name: Validate
        run: clj -Avalidate dev-resources/sample-validator
